### ISSUE TITLE
064-markers-render-html-inside-labels-example doesnt work with open layers 3.16

### ISSUE THREAD

**Issue by Xesenix** [tombatossals/angular-openlayers-directive#278]
I see this example: [markers-render-html-inside-labels-example](http://tombatossals.github.io/angular-openlayers-directive/examples/064-markers-render-html-inside-labels-example.html) was written using open layers 3.4. I suppose much has changes since than because when hovering over labels using open layers 3.16 i get this error: 

TypeError: Argument 1 of Node.appendChild does not implement interface Node.

You probably pass jquery/ angular object somewhere instead of native dom element when creating tool tip element.

Here is jsfidle example of my problem: https://jsfiddle.net/xesenix/1bm9zdLn/

Its basically the base example with open layers 3.16 instead of 3.4

**Comment by Xesenix** [comment]
I have changed:
   ```
 createOverlay: function(element, pos) {
            element.css('display', 'block');
            var ov = new ol.Overlay({
                position: pos,
                element: element[0],
                positioning: 'center-left'
            });

            return ov;
        }
```
That seams to work for me.
